from instance_type import InstanceType

f1_2xlarge = InstanceType(
    instance_family="f1",
    instance_size="2xlarge",
    free_tier_eligible=False,
    bare_metal=False,
    hypervisor="Xen",
    vcpus=8,
    architecture="x86_64",
    cores=8,
    valid_cores=[2, 4, 8],
    threads_per_core=1,
    valid_threads_per_core=[1],
    sustained_clock_speed=2.3,
    memory_gb=122.0,
    storage_gb=470,
    storage_type="NVMe SSD",
    network_performance="Up to 10 Gigabit",
    instance_storage_gb=470.0,
    gpu=True,
    gpu_count=1,
    gpu_memory_gb=64.0,
    eni=4,
    ipv6_support=True
)

f1_4xlarge = InstanceType(
    instance_family="f1",
    instance_size="4xlarge",
    free_tier_eligible=False,
    bare_metal=False,
    hypervisor="Xen",
    vcpus=16,
    architecture="x86_64",
    cores=16,
    valid_cores=[4, 8, 16],
    threads_per_core=1,
    valid_threads_per_core=[1],
    sustained_clock_speed=2.3,
    memory_gb=244.0,
    storage_gb=940,
    storage_type="NVMe SSD",
    network_performance="Up to 10 Gigabit",
    instance_storage_gb=940.0,
    gpu=True,
    gpu_count=2,
    gpu_memory_gb=128.0,
    eni=8,
    ipv6_support=True
)

f1_16xlarge = InstanceType(
    instance_family="f1",
    instance_size="16xlarge",
    free_tier_eligible=False,
    bare_metal=False,
    hypervisor="Xen",
    vcpus=64,
    architecture="x86_64",
    cores=64,
    valid_cores=[16, 32, 64],
    threads_per_core=1,
    valid_threads_per_core=[1],
    sustained_clock_speed=2.3,
    memory_gb=976.0,
    storage_gb=3760,
    storage_type="NVMe SSD",
    network_performance="25 Gigabit",
    instance_storage_gb=3760.0,
    gpu=True,
    gpu_count=8,
    gpu_memory_gb=512.0,
    eni=50,
    ipv6_support=True
)