from instance_type import InstanceType

hpc7a_12xlarge = InstanceType(
    instance_family="hpc7a",
    instance_size="12xlarge",
    free_tier_eligible=False,
    bare_metal=False,
    hypervisor="Nitro",
    vcpus=48,
    architecture="x86_64",
    cores=48,
    valid_cores=[12, 24, 48],
    threads_per_core=1,
    valid_threads_per_core=[1],
    sustained_clock_speed=3.6,
    memory_gb=96.0,
    storage_gb=None,
    storage_type=None,
    network_performance="Up to 100 Gigabit",
    instance_storage_gb=None,
    gpu=False,
    gpu_count=0,
    gpu_memory_gb=0,
    eni=15,
    ipv6_support=True
)

hpc7a_24xlarge = InstanceType(
    instance_family="hpc7a",
    instance_size="24xlarge",
    free_tier_eligible=False,
    bare_metal=False,
    hypervisor="Nitro",
    vcpus=96,
    architecture="x86_64",
    cores=96,
    valid_cores=[24, 48, 96],
    threads_per_core=1,
    valid_threads_per_core=[1],
    sustained_clock_speed=3.6,
    memory_gb=192.0,
    storage_gb=None,
    storage_type=None,
    network_performance="Up to 200 Gigabit",
    instance_storage_gb=None,
    gpu=False,
    gpu_count=0,
    gpu_memory_gb=0,
    eni=30,
    ipv6_support=True
)

hpc7a_48xlarge = InstanceType(
    instance_family="hpc7a",
    instance_size="48xlarge",
    free_tier_eligible=False,
    bare_metal=False,
    hypervisor="Nitro",
    vcpus=192,
    architecture="x86_64",
    cores=192,
    valid_cores=[48, 96, 192],
    threads_per_core=1,
    valid_threads_per_core=[1],
    sustained_clock_speed=3.6,
    memory_gb=384.0,
    storage_gb=None,
    storage_type=None,
    network_performance="Up to 400 Gigabit",
    instance_storage_gb=None,
    gpu=False,
    gpu_count=0,
    gpu_memory_gb=0,
    eni=60,
    ipv6_support=True
)